"use client";
import { useEffect, useState } from "react";
type Status = { status?: string; result?: { total?: number; cached?: number; already_cached?: number; failed?: number; failed_game_ids?: number[] } };
type Game = { id: number; name: string };
export default function CoverImageSync() {
 const [status,setStatus]=useState<Status|null>(null); const [error,setError]=useState<string|null>(null); const [games,setGames]=useState<Game[]>([]);
 const load=async()=>{const r=await fetch("/api/admin/games/sync-cover-images",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.detail||"Status failed");setStatus(x);return x as Status;};
 useEffect(()=>{void load().catch(()=>{});},[]);
 useEffect(()=>{if(status?.status!=="running")return;const i=setInterval(()=>void load().catch(e=>setError(e.message)),3000);return()=>clearInterval(i);},[status?.status]);
 const ids=status?.result?.failed_game_ids??[];
 useEffect(()=>{let dead=false;if(!ids.length){setGames([]);return;}void Promise.all(ids.map(async id=>{try{const r=await fetch(`/api/proxy/games/${id}`);const x=r.ok?await r.json():null;return{id,name:x?.name||`Game #${id}`};}catch{return{id,name:`Game #${id}`};}})).then(x=>{if(!dead)setGames(x);});return()=>{dead=true;};},[ids.join(",")]);
 const start=async()=>{setError(null);try{const r=await fetch("/api/admin/games/sync-cover-images",{method:"POST"});const x=await r.json();if(!r.ok)throw new Error(x.detail||"Could not start sync");setStatus(x.status?x:{status:"running"});}catch(e){setError(e instanceof Error?e.message:"Could not start sync");}};
 const r=status?.result;return <section style={{marginTop:18,borderTop:"1px solid var(--gc-border)",paddingTop:12}}><div style={{fontWeight:700,marginBottom:8}}>Cover images</div><button type="button" onClick={()=>void start()} disabled={status?.status==="running"} style={{background:"var(--gc-accent)",color:"#fff",border:0,borderRadius:8,padding:"9px 12px",fontWeight:700}}>{status?.status==="running"?"Syncing Cover Images…":"Sync Cover Images"}</button>{error&&<div role="alert" style={{color:"#fca5a5",marginTop:8}}>{error}</div>}{status&&status.status!=="idle"&&<div role="status" style={{marginTop:12,padding:12,border:"1px solid var(--gc-border)",borderRadius:8,background:"var(--gc-surface-raised)"}}><strong>{status.status==="completed"?"Cover image sync completed.":status.status==="running"?"Syncing cover images…":`Status: ${status.status}`}</strong>{r&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(140px, 1fr))",gap:8,marginTop:10}}><span>Total checked <b>{r.total??0}</b></span><span>Newly cached <b>{r.cached??0}</b></span><span>Already cached <b>{r.already_cached??0}</b></span><span>Failed <b>{r.failed??0}</b></span></div>}{games.length>0&&<div style={{marginTop:14,borderTop:"1px solid var(--gc-border)",paddingTop:10}}><strong>Games needing a cover</strong><div style={{display:"grid",gap:5,marginTop:7}}>{games.map(g=><a key={g.id} href={`/games/${g.id}`} target="_blank" rel="noopener noreferrer" style={{color:"#bfdbfe",width:"fit-content"}}>{g.name} ↗</a>)}</div></div>}</div>}</section>;
}
